"""create core tables

Revision ID: 29d02dfaf39a
Revises: 
Create Date: 2025-12-01 18:36:24.813844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d02dfaf39a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insider_transactions', sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_insider_transactions_filed_at'), 'insider_transactions', ['filed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insider_transactions_filed_at'), table_name='insider_transactions')
    op.drop_column('insider_transactions', 'filed_at')
    # ### end Alembic commands ###
